# Generated by Django 4.2.20 on 2025-04-25 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascota', '0006_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Contenido spam o engañoso'), ('ofensivo', 'Contenido ofensivo'), ('duplicado', 'Publicación duplicada'), ('otro', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='mascota.mascota')),
                ('usuario_reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
