# Generated by Django 4.2.20 on 2025-04-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_categoria_articulo'),
    ]

    operations = [
    ]
