# Generated by Django 4.2.20 on 2025-04-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_blog_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen principal (opcional si se suben otras imágenes)', null=True, upload_to='mascotas/'),
        ),
        migrations.CreateModel(
            name='ImagenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mascota.mascota')),
            ],
            options={
                'verbose_name': 'Imagen de Mascota',
                'verbose_name_plural': 'Imágenes de Mascotas',
                'ordering': ['orden'],
            },
        ),
    ]
