# Generated by Django 4.2.20 on 2025-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_alter_mascota_foto_imagenmascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde está la mascota', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal (opcional)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='region',
            field=models.CharField(blank=True, help_text='Región/Provincia/Estado', max_length=100, null=True),
        ),
    ]
