# Generated by Django 4.2.20 on 2025-04-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascota', '0005_mascota_ciudad_mascota_codigo_postal_mascota_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Incluye el código de país, ejemplo: +56912345678', max_length=15, null=True)),
                ('whatsapp', models.BooleanField(default=True, help_text='¿Desea ser contactado por WhatsApp?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
