# Generated by Django 4.2.20 on 2025-04-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
